#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2012 Huayra GNU/Linux
#
# Author Miguel Angel Garcia <miguel.garcia@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

from gi.repository import Gio
import gtk
import gtk.gdk
import webkit
import os
import sys
import subprocess
import urllib2

# Base Key en GSettings
BASE_KEY = "apps.huayra-bullets"


class BulletsBrowser(webkit.WebView):
    """
    Widget for browsing the bullets.
    """
    def __init__(self, gsettings, start_page):
        webkit.WebView.__init__(self)
        self.gsettings = gsettings
        self.get_property("settings").set_property(
            "enable-default-context-menu", False)
        self.connect('navigation-policy-decision-requested',
            self._on_navigate_decision)
        self.load_uri(start_page)

    def _on_navigate_decision(self, view, frame, req, action, decision):
        parts = req.get_uri().split("://", 1)
        if len(parts) == 2:
            if parts[0] == 'exec':
                #Lanzar comandos externos
                command = urllib2.unquote(parts[1])
                subprocess.Popen(command, shell=True)
                return True
            if parts[0] == 'ui':
                # Actions callable from pages.
                params = parts[1].split("?", 1)
                if params[0] == 'finalize':
                    for p in params:
                        if p == 'autostart':
                            gsettings.set_boolean("autostart", True)
                        elif p == 'no_autostart':
                            gsettings.set_boolean("autostart", False)
                    gtk.main_quit()
                return True
        return False


def build_app_window(gsettings, start_page):
    """
    Build application window.
    """
    sw = gtk.ScrolledWindow()
    bullet_browser = BulletsBrowser(gsettings, start_page)
    sw.add(bullet_browser)
    win = gtk.Window(gtk.WINDOW_TOPLEVEL)
    win.set_icon_from_file(
        "/usr/share/icons/gnome/48x48/apps/help-browser.png")
    win.add(sw)
    win.set_resizable(False)
    bullet_browser.set_size_request(600, 400)
    win.set_default_size(600, 400)
    win.set_title("Primeros pasos en Huayra")
    win.set_position(gtk.WIN_POS_CENTER)
    win.set_deletable(False)
    win.connect("destroy", gtk.main_quit)
    return win


if __name__ == '__main__':
    gsettings = Gio.Settings.new(BASE_KEY)
    win = build_app_window(gsettings,
        "file:///home/miguel/huayra/huayra-bullets/pages/bullets.html")
    win.show_all()
    gtk.main()
